version: '3.1'
services:
  db:
    restart: always
    image: postgres
    environment:
         - POSTGRES_USER=cclark
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      - "5442:5442"
    network_mode: "bridge"
volumes: 
  pgdata: