version: '3.1'
services:
  db:
    restart: always
    image: postgres
    environment:
      # you can change these to whatever you need
         - POSTGRES_USER=pgadmin 
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports:
      # Note that this is not the default port
      - "5442:5442"
    network_mode: "bridge"
volumes: 
  pgdata: